[[crun]]
arch = "aarch64"
git-tree-sha1 = "b352a0e64de5df8661b3679cef720c72f462c4c2"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "78e4ef05ecb580249268d153b5285bd6f749b779738abe7ee2ae29ebed2dd27e"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.18.0+0/crun.v1.18.0.aarch64-linux-gnu.tar.gz"
[[crun]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c67b111d39fe6ab1664398e92558e4714ea2cea"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "10be3cf40ffc43f955376d0c930109b4dea6ac1ce0d5d9c3c4ab8f9d71bf1d9b"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.18.0+0/crun.v1.18.0.armv6l-linux-gnueabihf.tar.gz"
[[crun]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9069e586e6e4dc11a3e9ee14377511eb9708aacf"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "f13ee4ee110420abcf72627f8bfcdc4a8feac933161ca5a789cbf64d523f5880"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.18.0+0/crun.v1.18.0.armv7l-linux-gnueabihf.tar.gz"
[[crun]]
arch = "i686"
git-tree-sha1 = "20cab972254be3cfeecc296d604b181858d80c03"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "316086f074aa73f6e814f7f5af1e610ca2b7226e9eac3d6a2d8836b403e4a00c"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.18.0+0/crun.v1.18.0.i686-linux-gnu.tar.gz"
[[crun]]
arch = "powerpc64le"
git-tree-sha1 = "eeba55bf64856cca7e084b803a52f56fca18db02"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "b3a6ffee3fced404b3c56989f77a92e40d0bf9963c3e8ac05d13bdec204b0f0c"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.18.0+0/crun.v1.18.0.powerpc64le-linux-gnu.tar.gz"
[[crun]]
arch = "x86_64"
git-tree-sha1 = "52960259d1bb92a0e5fb8b22bd6545ba69eae67d"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "50f68d581676bcb7dd145b62c12c101a7504162fea2dc4587478ff1d7a97fde4"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.18.0+0/crun.v1.18.0.x86_64-linux-gnu.tar.gz"
