[[crun]]
arch = "aarch64"
git-tree-sha1 = "892b3abeeaeef38d44eb736861391e02503092a8"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "bd79f9136b68bd0b48d552ca14acadb2aea9a1ba055de0fda4fde3b55bf8179a"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.8.0+0/crun.v1.8.0.aarch64-linux-gnu.tar.gz"
[[crun]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b1666e32a38d71037c6e8dee019b22939f3f3df1"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "b752aee1511956681ea6a8d7f36af207761ea4dc1826d6271ab6726d61056090"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.8.0+0/crun.v1.8.0.armv6l-linux-gnueabihf.tar.gz"
[[crun]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f1d0603c02fa380e7ae1a9e6e941acb6cd9f777e"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "14678841fa6875c1321b87dd2441afe24fcb484f1476e91bc37f5c29d194aca8"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.8.0+0/crun.v1.8.0.armv7l-linux-gnueabihf.tar.gz"
[[crun]]
arch = "i686"
git-tree-sha1 = "5adf66d38cfb97e090685075ff84a3e0df442139"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "f8fa533a023cd3e37c483c7222f39a9239677a5555c235e9c0f23bb9787be289"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.8.0+0/crun.v1.8.0.i686-linux-gnu.tar.gz"
[[crun]]
arch = "powerpc64le"
git-tree-sha1 = "7d98726b6bafa9599144ad9e5db8078e059c07cf"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "d8270f40634d14e1bfe76b478a6380fb5dd83eb68e571814615c8084c0ea1480"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.8.0+0/crun.v1.8.0.powerpc64le-linux-gnu.tar.gz"
[[crun]]
arch = "x86_64"
git-tree-sha1 = "239d7420b69279edb80beb2b3ee55903b11acbb3"
libc = "glibc"
os = "linux"

    [[crun.download]]
    sha256 = "fa1e6005a7c0850d43f5642788865d243d39b553110ae6a5e3f9822b2301663a"
    url = "https://github.com/JuliaBinaryWrappers/crun_jll.jl/releases/download/crun-v1.8.0+0/crun.v1.8.0.x86_64-linux-gnu.tar.gz"
